// Generated by Wrangler on Fri Jun 07 2024 05:36:36 GMT-0400 (Eastern Daylight Time)
// by running `wrangler types`

interface Env {
  DB: D1Database;
}

import "@cloudflare/next-on-pages";
declare global {
  interface CloudflareEnv {ce;
    DB: D1Database;
  }
}
